services:
  - type: web
    name: banqiao-house-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: MAX_RESULTS
        value: 10
      - key: VERIFY_SSL
        value: false
